<?php

$a=abs(-28);
echo "this is absolute value ".$a;
echo "<br>";
$b=sqrt(16);
echo "square of 16 is ".$b;
echo "<br>";
$c=rand(1,100);
echo "random number between 1 to 100 ".$c;
echo "<br>";
$d=round(3.7);
echo "round figure value ".$d;
echo "<br>";
$e=ceil(3.2);
echo "up to nearest integer ".$e;
echo "<br>";
$f=floor(3.8);
echo "down to nearest integer ".$f;
echo "<br>";
$g=pow(2,3);
echo "power of the number ".$g;
echo "<br>";
$h=max(5,8,3);
echo "find a maximum value ".$h;
echo "<br>";
$i=min(5,8,3);
echo "find minimum value ".$i;
echo "<br>";
$j=strlen("Hello world");
echo "return length of a string ".$j;
echo "<br>";
$k=strpos("hello,world!","world");
echo "find position of substring ".$k;
echo "<br>";
$l=str_replace("world","universe","hello, world");
echo "replaces string ".$l;
echo "<br>";
$m=substr("hello, world",0,5);
echo "return a position of a string ".$m;
echo "<br>";
$n=strtolower("HELLO DRASHTI");
echo "converting into lowercase ".$n;
echo "<br>";
$o=strtoupper("hello drashti");
echo "converting into upper ".$o;
echo "<br>";
$p=ucfirst("hello drashti");
echo "converting first latter into uppercase ".$p;
echo "<br>";
$q=strrev("hello world");
echo "reverse a string ".$q;
echo "<br>";
$r=trim("***drashti***","*");
echo "remove space and character ".$r;
echo "<br>";
$s=date("y-m-d H:i:s");
echo "formate of local date and time ".$s;
echo "<br>";
$t=time();
echo "unix timestamp ".$t;
echo "<br>";
$u=strtotime("2023-08-01");
echo "conver date&time into unix timestamp ".$u;
echo "<br>";
$v=gmdate("y-m-d H:i:s");
echo "formate a GMT ".$v;
echo "<br>";
$w=mktime(12,0,0,8,1,2023);
echo "creates a unix timestamp ".$w;
echo "<br>";
$x=date_default_timeZone_set("New_york");
echo "sets the default timezone ".$x;
echo "<br>";

?>